version: '3'
services:
 docker-app:
    image: app-medicamento
    ports:
      - "8080:8080"
    depends_on:
      - memories
 memories:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"