server:
  port: 9999

zuul:

  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  
  sensitiveHeaders:
  
  routes:
    oauth:
      stripPrefix: false
      serviceId: auth-server
    tipos:
      stripPrefix: false
      serviceId: medicamento-api
    medicamentos:
      stripPrefix: false
      serviceId: medicamento-api
    estoque:
      stripPrefix: false
      serviceId: medicamento-api
    solicitacao:
      stripPrefix: false
      serviceId: medicamento-api
    status:
      stripPrefix: false
      serviceId: medicamento-api
    
     
eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000